src/main/kotlin/Main.kt
src/main/kotlin/minesweeper/domain/BoardSize.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/CellType.kt
src/main/kotlin/minesweeper/domain/LengthNumber.kt
src/main/kotlin/minesweeper/domain/MinesweeperBoard.kt
src/main/kotlin/minesweeper/domain/MinesweeperGame.kt
src/main/kotlin/minesweeper/domain/MinesweeperGameResult.kt
src/main/kotlin/minesweeper/view/ResultView.kt
src/test/kotlin/minesweeper/MinesweeperBoardTest.kt

에러 핸들링을 sealed class 로 구현하는 것으로 수정해봤습니다. 
이 부분은 제가 처음 해보는 부분이라 좀 어려웠는데 맞게 구현한건지 확인 부탁 드립니다.
이외에 지뢰 개수 계산하는 부분 구현 완료했습니다.

Step2 - 지뢰찾기 (지뢰 개수)

---

src/main/kotlin/Result.kt
src/main/kotlin/controller/MineSweeperApp.kt
src/main/kotlin/model/Board.kt
src/main/kotlin/model/BoardSize.kt
src/main/kotlin/model/Coordinates.kt
src/main/kotlin/model/MineType.kt
src/main/kotlin/model/NumberOfMine.kt
src/main/kotlin/view/ResultView.kt
src/test/kotlin/model/BoardTest.kt
src/test/kotlin/model/LengthOfSideTest.kt

지뢰 찾기 (지뢰 개수) 기능을 구현하였습니다.
1단계 리뷰 건 포함하여 수정하였습니다.
https://github.com/next-step/kotlin-minesweeper/pull/6

[FEAT] 2단계 - 지뢰 찾기(지뢰 개수)

---

src/main/kotlin/Application.kt
src/main/kotlin/domain/Block.kt
src/main/kotlin/domain/BlockType.kt
src/main/kotlin/domain/Board.kt
src/main/kotlin/domain/BoardGenerator.kt
src/main/kotlin/domain/Location.kt
src/main/kotlin/domain/Mine.kt
src/main/kotlin/domain/NormalBlock.kt
src/main/kotlin/view/ResultView.kt
src/test/kotlin/domain/BlockTest.kt
src/test/kotlin/domain/BoardTest.kt

Step4 - 지뢰 찾기(리팩터링)

---

src/main/kotlin/controller/MineSweeperApp.kt
src/main/kotlin/model/Board.kt
src/main/kotlin/model/BoardMap.kt
src/main/kotlin/model/Coordinates.kt
src/main/kotlin/model/Gamer.kt
src/main/kotlin/model/MineType.kt
src/main/kotlin/model/Winner.kt
src/main/kotlin/view/ResultView.kt
src/test/kotlin/model/BoardTest.kt
src/test/kotlin/model/GamerTest.kt

지뢰 찾기 관련하여 작성해주신 리뷰들을 수정하였습니다.
감사합니다.:+1:

[FEAT] 4단계 - 지뢰 찾기(리팩터링)

---

src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/Point.kt
src/main/kotlin/minesweeper/domain/Points.kt
src/main/kotlin/minesweeper/startApp.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/ResultView.kt
src/test/kotlin/minesweeper/domain/BoardTest.kt
src/test/kotlin/minesweeper/domain/NotMineTest.kt
src/test/kotlin/minesweeper/domain/PointsTest.kt

[parkchu] 지뢰 찾기 3단계 - 지뢰 찾기(게임 실행)

---

src/main/kotlin/minesweeper/MineSweeperController.kt
src/main/kotlin/minesweeper/domain/CellManager.kt
src/main/kotlin/minesweeper/domain/MineMap.kt
src/main/kotlin/minesweeper/domain/MineSweeperApp.kt
src/main/kotlin/minesweeper/domain/cell/Cell.kt
src/main/kotlin/minesweeper/domain/cell/MineCell.kt
src/main/kotlin/minesweeper/domain/cell/NumberCell.kt
src/main/kotlin/minesweeper/domain/cell/Position.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/test/kotlin/minesweeper/domain/CellManagerTest.kt
src/test/kotlin/minesweeper/domain/MineMapTest.kt
src/test/kotlin/minesweeper/domain/cell/CellTest.kt
src/test/kotlin/minesweeper/domain/cell/NumberCellTest.kt
src/test/kotlin/minesweeper/domain/cell/PositionTest.kt

2단계 미션 제출합니다! 
많은 리뷰 해주시면 감사하겠습니다!

[namjackson] 4-2단계 mineSweeper Number

---

src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/ClosePoint.kt
src/main/kotlin/minesweeper/domain/Mine.kt
src/main/kotlin/minesweeper/domain/NotMine.kt
src/main/kotlin/minesweeper/domain/Point.kt
src/main/kotlin/minesweeper/domain/Points.kt
src/main/kotlin/minesweeper/startApp.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/ResultView.kt
src/test/kotlin/minesweeper/domain/BoardTest.kt
src/test/kotlin/minesweeper/domain/ClosePointTest.kt
src/test/kotlin/minesweeper/domain/NotMineTest.kt
src/test/kotlin/minesweeper/domain/PointsTest.kt

[parkchu] 지뢰 찾기 4단계 - 지뢰 찾기(리팩터링)

---

settings.gradle.kts
src/main/kotlin/BoardGenerator.kt
src/main/kotlin/Cell.kt
src/main/kotlin/Cells.kt
src/main/kotlin/Extension.kt
src/main/kotlin/InputView.kt
src/main/kotlin/MineSweeper.kt
src/main/kotlin/ResultView.kt
src/test/kotlin/BoardGeneratorTest.kt
src/test/kotlin/CellsTest.kt
src/test/kotlin/ExtensionTest.kt

지뢰 찾기를 변형한 프로그램을 구현한다.
- 높이와 너비, 지뢰 개수를 입력받을 수 있다.
- 지뢰는 눈에 잘 띄는 것으로 표기한다.
- 지뢰는 가급적 랜덤에 가깝게 배치한다.
마지막 미션이네요. 잘 부탁드리겠습니다 :)

Step1 지뢰 찾기(그리기)

---

src/main/kotlin/minesweeper/Main.kt
src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/NotFoundCellException.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/BoardTest.kt

4단계 - 지뢰 찾기(리팩터링) 

---

src/main/kotlin/minesweeper/Application.kt
src/main/kotlin/minesweeper/domain/board/BoardFactory.kt
src/main/kotlin/minesweeper/domain/position/Coordinate.kt
src/main/kotlin/minesweeper/domain/position/Position.kt
src/main/kotlin/minesweeper/domain/tile/Blank.kt
src/main/kotlin/minesweeper/domain/tile/Mine.kt
src/main/kotlin/minesweeper/domain/tile/Tile.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/position/CoordinateTest.kt
src/test/kotlin/minesweeper/domain/position/PositionTest.kt

안녕하세요 해리 :) 
step  2 구현이 조금 늦어졌어요. 
잘 부탁 드립니다!

[Step2] 지뢰 찾기(지뢰 개수)

---

settings.gradle.kts
src/main/kotlin/minesweeper/Runner.kt
src/main/kotlin/minesweeper/domain/BoomPosition.kt
src/main/kotlin/minesweeper/domain/BoomPositionMaker.kt
src/main/kotlin/minesweeper/domain/Mine.kt
src/main/kotlin/minesweeper/domain/MineMap.kt
src/main/kotlin/minesweeper/inputdata/MineGameCondition.kt
src/main/kotlin/minesweeper/inputdata/MineGameConfig.kt
src/main/kotlin/minesweeper/inputdata/PositiveNumber.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/BoomPositionMakerTest.kt
src/test/kotlin/minesweeper/domain/MineMapTest.kt
src/test/kotlin/minesweeper/inputdata/MineGameConditionTest.kt
src/test/kotlin/minesweeper/inputdata/MineGameConfigTest.kt
src/test/kotlin/minesweeper/inputdata/PositiveNumberTest.kt

커밋이 회사계정으로 됐어서ㅠ 커밋의 날짜이력이 다 날아갔네요 8ㅅ8
설계는 언제나 쉽지 않네요
- PositiveNumber 클래스를 사용을 해야할까가 고민입니다. 굳이 PositiveNumber가 아니어도 사전에 검증할 수 있을 것 같아서요. 오히려 맵 size도 같이 갖고있어 map 크기와 관련된 원자 클래스로 만들었으면 좀 나았겠다 싶기도하고.. 
- MineGameConfig 이 사용자 입력값이 너무 이곳저곳에 의존관계를 맺는것 같아 고민입니다.

1단계 - 지뢰 찾기(그리기)

---

src/main/kotlin/minesweeper/BoardGenerator.kt
src/main/kotlin/minesweeper/Cell.kt
src/main/kotlin/minesweeper/Cells.kt
src/main/kotlin/minesweeper/Extension.kt
src/main/kotlin/minesweeper/InputView.kt
src/main/kotlin/minesweeper/Location.kt
src/main/kotlin/minesweeper/MineSweeper.kt
src/main/kotlin/minesweeper/Position.kt
src/main/kotlin/minesweeper/ResultView.kt
src/main/kotlin/minesweeper/domain/BoardGenerator.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/Cells.kt
src/main/kotlin/minesweeper/domain/Location.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/test/kotlin/minesweeper/BoardGeneratorTest.kt
src/test/kotlin/minesweeper/CellsTest.kt
src/test/kotlin/minesweeper/ExtensionTest.kt
src/test/kotlin/minesweeper/LocationTest.kt
src/test/kotlin/minesweeper/PositionTest.kt
src/test/kotlin/minesweeper/domain/CellTest.kt
src/test/kotlin/minesweeper/domain/CellsTest.kt
src/test/kotlin/minesweeper/domain/LocationTest.kt
src/test/kotlin/minesweeper/domain/PositionTest.kt

안녕하세요!
https://github.com/next-step/kotlin-minesweeper/pull/49 
해당 pr이 아직 리뷰가 없어서, 먼저 step3을 진행했습니다.
step2와 함께 리뷰해주시면 감사하겠습니다 :)
ps. 커밋 내용에 step2 내용도 들어가 있는데, 4월 1일꺼부터 확인해주시면 됩니다.
https://github.com/next-step/kotlin-minesweeper/commit/1caaddb8e59335bf867f6f7a3ef739de39d55d9a
지뢰가 없는 인접한 칸이 모두 열리게 된다.

Step3 지뢰 찾기(게임 실행)

---

src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/Cells.kt

리뷰 해주신 내용을 반영합니다.
한달 동안 좋은 교육과정을 통하여 많이 배우고 갑니다..!
다음에도 이러한 기회가 또 있었으면 좋겠네요.
감사합니다!

Step4 지뢰 찾기(리팩터링)

---

src/main/kotlin/domain/Board.kt
src/main/kotlin/domain/Cell.kt
src/main/kotlin/domain/CellState.kt
src/main/kotlin/domain/MineLayer.kt
src/main/kotlin/domain/MineNumber.kt
src/main/kotlin/domain/MineSweeper.kt
src/main/kotlin/domain/Position.kt
src/main/kotlin/domain/PositionSelector.kt
src/main/kotlin/domain/RandomPositionSelector.kt
src/main/kotlin/dto/CellDto.kt
src/test/kotlin/domain/CellStateTest.kt
src/test/kotlin/domain/CellTest.kt
src/test/kotlin/domain/Fixture.kt

Step2 - 지뢰찾기(지뢰 개수)

---

src/main/kotlin/controller/Controller.kt
src/main/kotlin/domain/MineSweeper.kt
src/main/kotlin/domain/Position.kt
src/main/kotlin/dto/CellDto.kt
src/main/kotlin/dto/RowDto.kt
src/main/kotlin/view/InputView.kt
src/main/kotlin/view/OutputView.kt
src/test/kotlin/domain/Fixture.kt

벌써 기능상으로 마지막이군요.
Step1 에서 @BeokBeok  님께서 리뷰를 너무 잘해주셔서, 다음 단계 진행이 엄청 수월하네요.

Step3 - 지뢰 찾기(게임 실행) 구현

---

src/main/kotlin/minesweeper/Main.kt
src/main/kotlin/minesweeper/controller/MineSweeperController.kt
src/main/kotlin/minesweeper/domain/BlockCell.kt
src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/BoardFactory.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/MineCell.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/main/kotlin/minesweeper/domain/RandomGenerator.kt
src/main/kotlin/minesweeper/view/BoardDto.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/BoardFactoryTest.kt
src/test/kotlin/minesweeper/domain/DefaultRandomGeneratorTest.kt
src/test/kotlin/minesweeper/domain/PositionTest.kt

안녕하세요 리뷰어님! 
지뢰찾기 미션 잘 부탁드립니다 :)

Step1 drawing

---

src/main/kotlin/minesweeper/controller/MineSweeperController.kt
src/main/kotlin/minesweeper/domain/BlockCell.kt
src/main/kotlin/minesweeper/domain/BoardFactory.kt
src/main/kotlin/minesweeper/domain/BoardValues.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/CellFactory.kt
src/main/kotlin/minesweeper/domain/MineCell.kt
src/main/kotlin/minesweeper/domain/MineMap.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/main/kotlin/minesweeper/domain/Positions.kt
src/main/kotlin/minesweeper/view/BoardDto.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/BoardFactoryTest.kt
src/test/kotlin/minesweeper/domain/CellFactoryTest.kt
src/test/kotlin/minesweeper/domain/MineMapTest.kt
src/test/kotlin/minesweeper/domain/PositionTest.kt
src/test/kotlin/minesweeper/domain/PositionsTest.kt

Step2 count

---

src/main/kotlin/minesweeper/model/Cells.kt

- 1, 2, 3단계에서 4단계의 요구사항에 맞춰 진행한 것 같아 새로 만들어 보지는 못했습니다.
(새로 해 보고 싶어도 시간이 부족해 안될 것 같네요..)
- 3단계에서 주셨던 피드백을 반영해 반복문을 사용하지 않고 재귀 형태로 로직을 조금 개선 해 보았습니다.
- https://github.com/next-step/kotlin-minesweeper/pull/91#discussion_r764117488

🚀 4단계 - 지뢰 찾기(리팩터링)

---

src/main/kotlin/minesweeper/controller/MineSweeperController.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/main/kotlin/minesweeper/domain/board/Board.kt
src/main/kotlin/minesweeper/domain/board/BoardFactory.kt
src/main/kotlin/minesweeper/domain/board/BoardInGame.kt
src/main/kotlin/minesweeper/domain/board/BoardResult.kt
src/main/kotlin/minesweeper/domain/board/BoardValues.kt
src/main/kotlin/minesweeper/domain/board/MineCount.kt
src/main/kotlin/minesweeper/domain/board/MineMap.kt
src/main/kotlin/minesweeper/domain/cell/BlockCell.kt
src/main/kotlin/minesweeper/domain/cell/Cell.kt
src/main/kotlin/minesweeper/domain/cell/CellFactory.kt
src/main/kotlin/minesweeper/domain/cell/Cells.kt
src/main/kotlin/minesweeper/domain/cell/MineCell.kt
src/main/kotlin/minesweeper/domain/cell/MineMap.kt
src/main/kotlin/minesweeper/domain/position/Position.kt
src/main/kotlin/minesweeper/domain/position/Positions.kt
src/main/kotlin/minesweeper/view/BoardDto.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/board/BoardFactoryTest.kt
src/test/kotlin/minesweeper/domain/board/BoardInGameTest.kt
src/test/kotlin/minesweeper/domain/board/MineMapTest.kt
src/test/kotlin/minesweeper/domain/cell/CellFactoryTest.kt
src/test/kotlin/minesweeper/domain/cell/CellsTest.kt
src/test/kotlin/minesweeper/domain/cell/MineMapTest.kt
src/test/kotlin/minesweeper/domain/position/PositionTest.kt
src/test/kotlin/minesweeper/domain/position/PositionsTest.kt

안녕하세요 리뷰어님!
이전 코멘트에 대한 질문 https://github.com/next-step/kotlin-minesweeper/pull/86#discussion_r765729340 이 있습니다.
이번에도 좋은 리뷰 부탁드립니다 :)

Step3 click

---

src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/block/Block.kt
src/main/kotlin/minesweeper/domain/block/BlockGenerator.kt
src/main/kotlin/minesweeper/domain/block/Blocks.kt
src/main/kotlin/minesweeper/domain/block/Mine.kt
src/main/kotlin/minesweeper/domain/block/None.kt
src/main/kotlin/minesweeper/domain/block/Position.kt
src/main/kotlin/minesweeper/views/OutputView.kt
src/test/kotlin/minesweeper/domain/BoardTest.kt
src/test/kotlin/minesweeper/domain/block/BlocksTest.kt

안녕하세요, 리뷰어님 
마지막 미션 제출합니다.  피드백 부분을 수정하고 리팩터링하였습니다.

[Step4] 지뢰 찾기(리팩터링)

---

src/main/kotlin/MinesWeeperApplication.kt
src/main/kotlin/controller/BoardController.kt

따로 리팩토링없이 step3 의 피드백만 반영하였습니다.
그동안 리뷰해주시느라 수고하셨습니다!
많이 배웠습니다.
감사합니다 😄

step4 리팩토링

---

src/main/kotlin/minesweeper/controller/MinesweeperController.kt
src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/Cells.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/BoardTest.kt
src/test/kotlin/minesweeper/CellTest.kt
src/test/kotlin/minesweeper/CellsTest.kt
src/test/kotlin/minesweeper/PositionTest.kt

Step2 - 지뢰 찾기(지뢰 개수)

---

src/main/kotlin/domain/Brick.kt
src/main/kotlin/domain/Coordinate.kt
src/main/kotlin/domain/Mine.kt
src/main/kotlin/domain/MineBoard.kt
src/main/kotlin/domain/MineFactory.kt
src/main/kotlin/main.kt
src/main/kotlin/view/UI.kt
src/test/kotlin/domain/MineBoardTest.kt

+ 높이, 너비, 지뢰 입력받기
+ 좌표 값을 통해 지뢰를 심기
+ 지뢰 판을 출력하기
+ 테스트 코드 추가

Step 1. 지뢰 찾기(그리기)

---

src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/CellState.kt
src/main/kotlin/minesweeper/domain/Cells.kt
src/main/kotlin/minesweeper/domain/CellsExist.kt
src/main/kotlin/minesweeper/domain/CellsNotExist.kt
src/main/kotlin/minesweeper/domain/CellsOpener.kt
src/main/kotlin/minesweeper/domain/MineCellState.kt
src/main/kotlin/minesweeper/domain/NonMineCellState.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/CellStateTest.kt
src/test/kotlin/minesweeper/domain/CellsTest.kt
src/test/kotlin/minesweeper/domain/FixtureMineSweeper.kt

리뷰어님 안녕하세요~
드디어 마지막 미션의 마지막 pr 요청 이네요. 
코틀린에 대해 배워가는 부분이 많아서 그런지 시간이 참 빠르게 지나간것 같다는 생각이 드네요.
이번 4단계에서는 기존 3단계에서 요청주신 부분을 중점으로 수정했습니다. 
이번 마지막 리뷰도 잘 부탁드립니다!! 😁😁😁

4단계 - 지뢰 찾기(리팩터링)

---

src/main/kotlin/minesweeper/controller/MineSweeper.kt
src/main/kotlin/minesweeper/model/board/Board.kt
src/main/kotlin/minesweeper/model/board/BoardState.kt
src/main/kotlin/minesweeper/model/cell/Cell.kt
src/main/kotlin/minesweeper/model/cell/RandomMineLocator.kt
src/main/kotlin/minesweeper/view/output/ConsoleOutputView.kt
src/main/kotlin/minesweeper/view/output/OutputView.kt
src/test/kotlin/minesweeper/controller/MineSweeperTest.kt
src/test/kotlin/minesweeper/fixture/Boards.kt
src/test/kotlin/minesweeper/model/board/BoardTest.kt

State pattern 을 적용했습니다. 리뷰 잘 부탁드립니다.

MineSweeper : Step 4 (Refactoring)

---

src/main/kotlin/minesweeper/controller/MineSweeperBoardController.kt
src/main/kotlin/minesweeper/domain/MinGeneratorStrategy.kt
src/main/kotlin/minesweeper/domain/MineSearchDirection.kt
src/main/kotlin/minesweeper/domain/MineSweeperBoard.kt
src/main/kotlin/minesweeper/domain/MineSweeperBoardFactory.kt
src/main/kotlin/minesweeper/domain/MineSweeperResult.kt
src/main/kotlin/minesweeper/domain/Position.kt
src/main/kotlin/minesweeper/domain/Zone.kt
src/main/kotlin/minesweeper/domain/Zones.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/OutputView.kt
src/test/kotlin/minesweeper/domain/MineSweeperBoardFactoryKtTest.kt
src/test/kotlin/minesweeper/domain/ZoneTest.kt
src/test/kotlin/minesweeper/domain/ZonesTest.kt

형준님 항상 꼼꼼한 리뷰 감사드립니다. 😆 
2단계 머지하면서 주셨던 코멘트 반영해서 3단계 미션 진행하였습니다. 😃
이번 미션도 잘 부탁드립니다. 🙇‍♂️

3단계 - 지뢰 찾기(게임 실행)

---

src/main/kotlin/MainController.kt
src/main/kotlin/domain/Field.kt
src/main/kotlin/domain/GameStatus.kt
src/main/kotlin/domain/LocationOfMines.kt
src/main/kotlin/domain/Row.kt
src/main/kotlin/domain/Rows.kt
src/main/kotlin/domain/block/Block.kt
src/main/kotlin/domain/block/Land.kt
src/main/kotlin/domain/block/Mine.kt
src/main/kotlin/domain/block/OpenAbleBlock.kt
src/main/kotlin/domain/coord/AbstractCoordinate.kt
src/main/kotlin/domain/coord/Coordinate.kt
src/main/kotlin/domain/coord/RelativeCoordinate.kt
src/main/kotlin/domain/pos/AbstractPos.kt
src/main/kotlin/view/InputView.kt
src/main/kotlin/view/ResultView.kt
src/test/kotlin/domain/FieldTest.kt
src/test/kotlin/domain/RowTest.kt
src/test/kotlin/domain/RowsTest.kt
src/test/kotlin/domain/generator/RandomFieldGeneratorTest.kt

안녕하세요 리뷰어님
3단계 요구사항 구현 후 리뷰 요청 드립니다.
3단계도 잘부탁드립니다.🙏

🚀 3단계 - 지뢰 찾기(게임 실행)

---

src/main/kotlin/domains/GameMap.kt
src/main/kotlin/domains/MineBlock.kt
src/test/kotlin/domains/GameMapTest.kt
src/test/kotlin/domains/OpenResultTest.kt
src/test/kotlin/domains/PositionTest.kt

마지막 PR이네요
정말 감사했습니다!
테스트코드 보안해서 마무리 했습니다
덕분에 많이 성장한것같아요 
감사합니다

step-4 테스트코드 보안

---

README.md
build.gradle.kts
src/main/kotlin/controller/MineSweeperGame.kt
src/main/kotlin/model/MineBoard.kt
src/main/kotlin/model/MineBoardProvider.kt
src/main/kotlin/model/MineInstallation.kt
src/main/kotlin/model/MineMark.kt
src/main/kotlin/model/Position.kt
src/main/kotlin/model/RandomPositionSelector.kt
src/main/kotlin/view/InputView.kt
src/main/kotlin/view/OutputView.kt
src/test/kotlin/model/MineBoardProviderTest.kt
src/test/kotlin/model/MineBoardTest.kt
src/test/kotlin/model/MineInstallationTest.kt
src/test/kotlin/model/PositionTest.kt
src/test/kotlin/model/RandomPositionSelectorTest.kt

안녕하세요 박찬인 리뷰어님!!
TDD, 클린 코드 with Kotlin 지뢰 찾기 미션에 참여하게 된 한용희입니다. 🙇‍♂️
만나뵙게 되어 반갑습니다! 👋
각 영역에 대해 최대한 역할을 분리 해보려고 노력해봤는데
잘 구현된 방향인지 모르겠네요 🤔
그럼 앞으로 지뢰찾기 미션 잘 부탁드리겠습니다!🙇‍♂️🙇‍♂️🙇‍♂️

🚀 1단계 - 지뢰 찾기(그리기)

---

build.gradle.kts
src/main/kotlin/MineSweeper.kt
src/main/kotlin/MineSweeperMain.kt
src/main/kotlin/map/MapElement.kt
src/main/kotlin/map/MapElementType.kt
src/main/kotlin/map/MineMap.kt
src/main/kotlin/map/position/Position.kt
src/main/kotlin/map/position/selector/MinePositionSelector.kt
src/main/kotlin/map/position/selector/RandomMinePositionSelector.kt
src/main/kotlin/model/Height.kt
src/main/kotlin/model/MineCount.kt
src/main/kotlin/model/Width.kt
src/main/kotlin/view/InputView.kt
src/main/kotlin/view/OutputView.kt
src/main/kotlin/view/StdinInputView.kt
src/main/kotlin/view/StdoutOutputView.kt
src/test/kotlin/map/MineMapTest.kt
src/test/kotlin/model/HeightTest.kt
src/test/kotlin/model/MineCountTest.kt
src/test/kotlin/model/WidthTest.kt

안녕하세요 리뷰어님~!
지뢰찾기 첫 미션입니다. 잘 부탁드립니다

feature(step1): 지뢰찾기(그리기)

---

src/test/kotlin/minesweeper/domain/position/PositionHelper.kt

마무리하고자 테스트 헬퍼 하나 수정했습니다..!
덕분에 많이 배웠습니다.
리팩토링 할 부분이 분명히 있지만.. 시간적으로 여유가 없어서 아쉽네요ㅠ 좀 더 피드백 받으면서 수정했으면 좋겠지만
여기서 마무리하고자 합니다.
지금까지 피드백 감사합니다!

Step4 : 지뢰 찾기(리팩터링)

---

src/main/kotlin/minesweeper/domain/Board.kt
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/Point.kt
src/main/kotlin/minesweeper/ui/BoardPrinter.kt
src/test/kotlin/minesweeper/domain/CellTest.kt
src/test/kotlin/minesweeper/domain/PointTest.kt
src/test/kotlin/minesweeper/fixture/cell.kt

2단계 - 지뢰 찾기(지뢰 개수)

---

src/main/kotlin/domain/game/MineSweeperGame.kt
src/main/kotlin/domain/game/OpenResult.kt
src/main/kotlin/domain/map/MapCapture.kt
src/main/kotlin/domain/map/MineMap.kt
src/main/kotlin/view/MineSweeperController.kt
src/main/kotlin/view/MineSweeperResultView.kt
src/test/kotlin/domain/game/MineSweeperGameTest.kt
src/test/kotlin/domain/map/MineMapTest.kt
src/test/kotlin/domain/map/RealMineMapFactoryTest.kt

리뷰어님 안녕하세요. 4단계 미션 리뷰 요청 드립니다.
슬랙으로 말씀 드린대로, 4단계 미션은 3단계 미션의 피드백 정도만 반영했습니다.
지뢰 찾기 미션 꼼꼼하게 살펴봐주셔서 감사드립니다. 정말 고생하셨습니다 :)

[Step4] 지뢰찾기 (리팩터링)

---

src/main/kotlin/minesweeper/domain/Minesweeper.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper2/Minesweeper2Application.kt
src/main/kotlin/minesweeper2/controller/MineSweeperController.kt
src/main/kotlin/minesweeper2/domain/Col.kt
src/main/kotlin/minesweeper2/domain/Cols.kt
src/main/kotlin/minesweeper2/domain/FindPosition.kt
src/main/kotlin/minesweeper2/domain/Mine.kt
src/main/kotlin/minesweeper2/domain/MineCount.kt
src/main/kotlin/minesweeper2/domain/Minesweeper.kt
src/main/kotlin/minesweeper2/domain/Position.kt
src/main/kotlin/minesweeper2/domain/Positions.kt
src/main/kotlin/minesweeper2/domain/Row.kt
src/main/kotlin/minesweeper2/domain/Rows.kt
src/main/kotlin/minesweeper2/model/PositionLocation.kt
src/main/kotlin/minesweeper2/view/InputView.kt
src/main/kotlin/minesweeper2/view/ResultView.kt
src/test/kotlin/minesweeper/domain/MinesweeperTest.kt
src/test/kotlin/minesweeper2/domain/ColsTest.kt
src/test/kotlin/minesweeper2/domain/MineCountTest.kt
src/test/kotlin/minesweeper2/domain/MineTest.kt
src/test/kotlin/minesweeper2/domain/MinesweeperTest.kt
src/test/kotlin/minesweeper2/domain/PositionsTest.kt
src/test/kotlin/minesweeper2/domain/RowsTest.kt

안녕하세요 리뷰어님!
마지막 미션 코드리뷰 요청합니다 !
TDD 기반으로 완전히 새로 만들지는 못했고
기존 테스트 재활용 하여 minesweeper2 package 만들어서 
기존 아키텍처 리팩토링 진행 하였습니다.
MinePosition 관련 도메인 2개 제거 하였고, 기존 Pair 사용하던 로직 새로운 모델 사용하는 정도 리팩토링 한 것 같습니다.
지뢰찾기 피드백 고생 많으셨습니다.
많이 배웠습니다 !
감사합니다.

[Step4] TDD 기반 지뢰찾기 

---

README.md
build.gradle.kts
src/main/kotlin/minesweeper/domain/Cell.kt
src/main/kotlin/minesweeper/domain/MineCreator.kt
src/main/kotlin/minesweeper/domain/MineSweeper.kt
src/main/kotlin/minesweeper/domain/MineSweeperSize.kt
src/main/kotlin/minesweeper/main.kt
src/main/kotlin/minesweeper/view/InputView.kt
src/main/kotlin/minesweeper/view/MineSweeperController.kt
src/main/kotlin/minesweeper/view/ResultView.kt
src/test/kotlin/minesweeper/MineCreatorTest.kt

안녕하세요 리뷰어님!😊
지뢰 찾기 미션 잘 부탁드리겠습니다!
요구사항이 많지 않다고 판단하고 작업하다보니 실질적인 커밋이 하나로 생성되었습니다. 리뷰해주시는 데에 어려움이 있을까 걱정이네요🙇‍♂️
지뢰를 생성하는 방법에 대해 많은 고민을 했습니다.
사실 고민의 결과가 만족스럽지 않은데요, 간단한 방향을 제시해주시면 감사드리겠습니다🙇‍♂️

[step1] 지뢰 찾기(그리기)

---

src/main/kotlin/controller/GameManager.kt
src/main/kotlin/controller/Main.kt
src/main/kotlin/domain/Boom.kt
src/main/kotlin/domain/Field.kt
src/main/kotlin/domain/Finished.kt
src/main/kotlin/domain/FoundAll.kt
src/main/kotlin/domain/Ready.kt
src/main/kotlin/domain/Running.kt
src/main/kotlin/domain/Status.kt
src/main/kotlin/domain/Waiting.kt

> 전달드리고 싶었던 코멘트 의도는 "지뢰찾기 게임 전체를 다루는 controller 하위 계층이 하나 더 존재하면 어떨까?" 였습니다.
기존 field 에게 종료 여부와 클릭 결과가 폭발인지 아닌지를 함께 묻고 있었는데,
이 내용이 한겹 더 감싸져서 controller 는 오로지 "게임이 끝났는가?" 여부만 판단하길 기대했습니다.
피드백 주신 내용이 controller.Main을 돕는 클래스를 하나 더 두는것인지,
controller 안에서는 게임이 끝났는지만 확인하도록 하는것인지
아니면 둘 다인지 모르겠어서 
강의에서 나왔던 현상태의 객체화 적용해 두가지 다 만족시켜봤습니다

Step4 - 리팩토링
